// import mongoose,it creates an interface with our database, it is to create a schema, a data model, allows to modify, delete, create ...
const mongoose = require("mongoose");

// create the schema, use the schema() function to which we pass an object that dictates the fields

//_id: { type: String, required: true }, // not necessary since automatically generated by mongoose
// add the field name in our configuration object, create an object for each field to configure the fields
// add the type of field, add the required configuration, without userId we cannot add post
const postSchema = new mongoose.Schema(
  {
    userId: { type: String, required: true },
    post: { type: String },
    imageUrl: { type: String },
    likes: { type: Number, default: 0 },
    dislikes: { type: Number, default: 0 },
    usersLiked: { type: [String] },
    usersDisliked: { type: [String] },
    userName: { type: String },
    authorImg: { type: String },
  },

  { timestamps: true }
);

// If you set timestamps: true, Mongoose will add two properties of type Date to your schema:
// createdAt: a date representing when the post was created
// updatedAt: a date representing when the post was last updated

module.exports = mongoose.model("Post", postSchema);
